apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.fullname" . }}-env
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
stringData:
  # avoid errors if no secrets are provided in values
  empty: ""
data:
  {{- if .Values.mastodon.settings.otpSecret }}
  OTP_SECRET: {{ .Values.mastodon.settings.otpSecret | b64enc }}
  {{- end }}
  {{- if .Values.mastodon.settings.secretKeyBase }}
  SECRET_KEY_BASE: {{ .Values.mastodon.settings.secretKeyBase | b64enc }}
  {{- end }}
  {{- if .Values.mastodon.settings.vapidPrivateKey }}
  VAPID_PRIVATE_KEY: {{ .Values.mastodon.settings.vapidPrivateKey | b64enc}}
  {{- end }}
  {{- if .Values.mastodon.settings.vapidPublicKey }}
  VAPID_PUBLIC_KEY: {{ .Values.mastodon.settings.vapidPublicKey| b64enc}}
  {{- end }}
  {{- if .Values.mastodon.settings.smtp.password }}
  SMTP_PASSWORD: {{ .Values.mastodon.settings.smtp.password | b64enc }}
  {{- end }}
