apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mastodon.fullname" . }}-varnish-s3
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.varnishS3.deployment.autoscaling.enabled false }}
  replicas: {{ .Values.varnishS3.deployment.replicas }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels.global" . | nindent 6 }}
      {{- include "mastodon.selectorLabels.varnishS3" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.varnishS3.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mastodon.selectorLabels.global" . | nindent 8 }}
        {{- include "mastodon.selectorLabels.varnishS3" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.varnishS3.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-varnish-s3
          {{- if .Values.varnishS3.deployment.securityContext}}
          securityContext:
            {{- toYaml .Values.varnishS3.deployment.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.varnishS3.deployment.image.repository }}:{{ .Values.varnishS3.deployment.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args:
            - "-c"
            - >-
              varnishd -F -f /etc/varnish/default.vcl -a http=:8080,HTTP -p feature=+http2 -s malloc,100M
              -p workspace_session=1024 -p workspace_thread=4096 -p workspace_client=131072
              -p workspace_backend=131072 -p listen_depth=16383 -p http_resp_hdr_len=65536
              -p http_resp_size=98304 -p workspace_backend=131072 -p thread_pool_min=200
              -p thread_pool_max=5000
          imagePullPolicy: {{ .Values.mastodon.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /pixel.gif
              port: http
          readinessProbe:
            httpGet:
              path: /pixel.gif
              port: http
          resources:
            {{- toYaml .Values.varnishS3.deployment.resources | nindent 12 }}
          volumeMounts:
            - name: varnish-tmp
              mountPath: /var/lib/varnish/varnishd
            - name: varnish-config
              mountPath: /etc/varnish/default.vcl
              subPath: default.vcl
          {{- range .Values.varnishS3.additionalMounts }}
            - {{- toYaml .volumeMount | nindent 14 }}
          {{- end }}
      volumes:
        - name: varnish-config
          configMap:
            name: {{ include "mastodon.fullname" . }}-varnish-s3-config
        - name: varnish-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
      {{- range .Values.varnishS3.additionalMounts }}
        - {{- toYaml .volume | nindent 10 }}
      {{- end }}
      {{- with .Values.varnishS3.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.varnishS3.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.varnishS3.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
