{{- if .Values.varnishS3.deployment.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mastodon.fullname" . }}-varnish-s3
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mastodon.fullname" . }}-varnish-s3
  minReplicas: {{ .Values.varnishS3.deployment.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.varnishS3.deployment.autoscaling.maxReplicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 90
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 3
          periodSeconds: 15
      selectPolicy: Max
  metrics:
    {{- if .Values.varnishS3.deployment.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: {{ .Values.varnishS3.deployment.autoscaling.targetMemoryUtilizationPercentage }}
          type: Utilization
    {{- end }}
    {{- if .Values.varnishS3.deployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: {{ .Values.varnishS3.deployment.autoscaling.targetCPUUtilizationPercentage }}
          type: Utilization
    {{- end }}
{{- end }}
