{{- if .Values.mediaIngress.enabled -}}
{{- if and .Values.mediaIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.mediaIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.mediaIngress.annotations "kubernetes.io/ingress.class" .Values.mediaIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "mastodon.fullname" . }}-media-ingress-varnish
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
  {{- with .Values.mediaIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.mediaIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.mediaIngress.className }}
  {{- end }}
  {{- if .Values.mediaIngress.tls }}
  tls:
    {{- range .Values.mediaIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.mediaIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "mastodon.fullname" $ }}-varnish-s3
                port:
                  number: {{ $.Values.varnishS3.service.port }}
              {{- else }}
              serviceName: {{ include "mastodon.fullname" $ }}-varnish-s3
              servicePort: {{ $.Values.varnishS3.service.port }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
