---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon.fullname" . }}-varnish-s3
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.varnishS3.service.type }}
  ports:
    - port: {{ .Values.varnishS3.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mastodon.selectorLabels.global" . | nindent 4 }}
    {{- include "mastodon.selectorLabels.varnishS3" . | nindent 4 }}
