apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mastodon.fullname" . }}-web
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.mastodon.web.deployment.autoscaling.enabled false }}
  replicas: {{ .Values.mastodon.web.deployment.replicas }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels.global" . | nindent 6 }}
      {{- include "mastodon.selectorLabels.web" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.mastodon.web.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mastodon.selectorLabels.global" . | nindent 8 }}
        {{- include "mastodon.selectorLabels.web" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.mastodon.web.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.mastodon.image.repository }}:{{ .Values.mastodon.image.tag | default .Chart.AppVersion }}"
          args:
          - bash
          - -c
          - rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000
          imagePullPolicy: {{ .Values.mastodon.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.mastodon.web.deployment.securityContext | nindent 12 }}
          volumeMounts:
          {{- if .Values.mastodon.web.settings.rwSplit.enabled }}
            - mountPath: /opt/mastodon/config/database.yml
              name: db-config
              subPath: database.yml
          {{- end }}
          {{- range .Values.mastodon.web.additionalMounts }}
            - {{- toYaml .volumeMount | nindent 14 }}
          {{- end }}
          env:
            - name: WEB_CONCURRENCY
              value: {{ .Values.mastodon.web.settings.concurrency | quote }}
            - name: MAX_THREADS
              value: {{ .Values.mastodon.web.settings.maxThreads | quote }}
          {{- with .Values.mastodon.extraEnv.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mastodon.web.extraEnv.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "mastodon.fullname" . }}-env
            - secretRef:
                name: {{ include "mastodon.fullname" . }}-env
            {{- if .Values.mastodon.extraEnv.fromConfigMap }}
            - configMapRef:
                name: {{ .Values.mastodon.extraEnv.fromConfigMap }}
            {{- end }}
            {{- if .Values.mastodon.extraEnv.fromSecret }}
            - secretRef:
                name: {{ .Values.mastodon.extraEnv.fromSecret }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.mastodon.web.deployment.resources | nindent 12 }}
      volumes:
      {{ if .Values.mastodon.web.settings.rwSplit.enabled }}
        - name: db-config
          configMap:
            name: {{ include "mastodon.fullname" . }}-mastodon-db-config-rw-split
      {{ end }}
      {{ range .Values.mastodon.web.additionalMounts }}
        - {{- toYaml .volume | nindent 10 }}
      {{ end }}
      {{ with .Values.mastodon.web.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mastodon.web.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mastodon.web.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
