apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon.fullname" . }}-web
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mastodon.web.service.type }}
  ports:
    - port: {{ .Values.mastodon.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mastodon.selectorLabels.global" . | nindent 4 }}
    {{- include "mastodon.selectorLabels.web" . | nindent 4 }}
