apiVersion: v2
name: mastodon
description: Rivals.space Mastodon helm chart
icon: https://joinmastodon.org/logos/logo-purple.svg
type: application
version: 1.0.1
appVersion: "v4.0.2"
dependencies:
  - name: redis
    version: 17.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
