apiVersion: v2
name: mastodon
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "v4.0.2"
dependencies:
  - name: redis
    version: 17.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
