apiVersion: v2
name: mastodon
description: Rivals.space Mastodon helm chart
icon: https://joinmastodon.org/logos/logo-purple.svg
type: application
version: 2.3.1
appVersion: "1.0.1"
maintainers:
  - name: emilweth
    email: coucou@emi.cool
dependencies:
  - name: redis
    version: 17.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
