apiVersion: v2
name: mastodon
description: Rivals.space Mastodon helm chart
icon: https://joinmastodon.org/logos/logo-purple.svg
type: application
version: 3.1.0
appVersion: "1.6.0"
maintainers:
  - name: emilweth
    email: coucou@emi.cool
dependencies:
  - name: keda
    version: 2.8.2
    repository: https://charts.softonic.io
    condition: keda.enabled
  - name: redis
    version: 17.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
