apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mastodon.fullname" . }}-nginx-reverse-config
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /tmp/nginx.pid;

    load_module modules/ngx_http_brotli_filter_module.so;
    load_module modules/ngx_http_brotli_static_module.so;

    events {
        worker_connections  1024;
    }

    http {
        proxy_temp_path /tmp/proxy_temp;
        client_body_temp_path /tmp/client_temp;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;

        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        set_real_ip_from 10.0.0.0/8;
        real_ip_header X-Forwarded-For;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        tcp_nopush      on;
        tcp_nodelay     on;

        keepalive_timeout  65;

        include /etc/nginx/conf.d/*.conf;
    }
  default.conf: |

    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=CACHE:10m inactive=7d max_size=1g;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 8080;

        server_name _;

        keepalive_timeout    70;
        sendfile             on;
        client_max_body_size 0;

        root /opt/mastodon/public/;

        brotli on;
        brotli_comp_level 6;
        brotli_static on;
        brotli_types application/atom+xml application/javascript application/json application/rss+xml
                     application/vnd.ms-fontobject application/x-font-opentype application/x-font-truetype
                     application/x-font-ttf application/x-javascript application/xhtml+xml application/xml
                     font/eot font/opentype font/otf font/truetype image/svg+xml image/vnd.microsoft.icon
                     image/x-icon image/x-win-bitmap text/css text/javascript text/plain text/xml;

        location / {
            try_files $uri @proxy;
        }

        location = /sw.js {
            add_header Cache-Control "public, max-age=604800, must-revalidate";
            add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
            try_files $uri @proxy;
        }

        location ~ ^/assets/ {
          add_header Cache-Control "public, max-age=2419200, must-revalidate";
          add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
          try_files $uri @proxy;
        }

        location ~ ^/packs/ {
          add_header Cache-Control "public, max-age=2419200, must-revalidate";
          add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
          try_files $uri @proxy;
        }

        location ~ ^/shortcuts/ {
          add_header Cache-Control "public, max-age=2419200, must-revalidate";
          add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
          try_files $uri @proxy;
        }

        location ~ ^/sounds/ {
          add_header Cache-Control "public, max-age=2419200, must-revalidate";
          add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
          try_files $uri @proxy;
        }

        location ~ ^/system/ {
          add_header Cache-Control "public, max-age=2419200, immutable";
          add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
          try_files $uri @proxy;
        }


        location @proxy {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Proxy "";
            proxy_pass_header Server;

            proxy_pass http://{{ include "mastodon.fullname" . }}-web.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.mastodon.web.service.port }};
            proxy_buffering on;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_cache CACHE;
            proxy_cache_valid 200 7d;
            proxy_cache_valid 410 24h;
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
            add_header X-Nginx-Cached $upstream_cache_status;

            tcp_nodelay on;
        }

        error_page 500 501 502 503 504 /500.html;
    }
    server {
        listen 8081;
        location /status {
            stub_status on;
        }
    }
