apiVersion: v2
name: libretranslate
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "v1.3.9"
maintainers:
  - name: emilweth
    email: coucou@emi.cool
icon: https://libretranslate.com/static/icon.svg
