apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mastodon.fullname" . }}-nginx-statics
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.nginxReverse.deployment.autoscaling.enabled false }}
  replicas: {{ .Values.nginxReverse.deployment.replicas }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels.global" . | nindent 6 }}
      {{- include "mastodon.selectorLabels.nginxReverse" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.nginxReverse.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mastodon.selectorLabels.global" . | nindent 8 }}
        {{- include "mastodon.selectorLabels.nginxReverse" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.nginxReverse.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-nginx-statics
          {{- if .Values.nginxReverse.deployment.securityContext}}
          securityContext:
            {{- toYaml .Values.nginxReverse.deployment.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.nginxReverse.deployment.image.repository }}:{{ $.Values.nginxReverse.deployment.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.mastodon.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: health
          readinessProbe:
            httpGet:
              path: /status
              port: health
          resources:
            {{- toYaml .Values.nginxReverse.deployment.resources | nindent 12 }}
          volumeMounts:
          {{- range .Values.nginxReverse.additionalMounts }}
            - {{- toYaml .volumeMount | nindent 14 }}
          {{- end }}
      volumes:
      {{- range .Values.nginxReverse.additionalMounts }}
        - {{- toYaml .volume | nindent 10 }}
      {{- end }}
      {{- with .Values.nginxReverse.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginxReverse.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginxReverse.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
