apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon.fullname" . }}-nginx-statics
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginxReverse.service.type }}
  ports:
    - port: {{ .Values.nginxReverse.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mastodon.selectorLabels.global" . | nindent 4 }}
    {{- include "mastodon.selectorLabels.nginxReverse" . | nindent 4 }}
