apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mastodon.fullname" . }}-streaming
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.mastodon.streaming.deployment.autoscaling.enabled false}}
  replicas: {{ .Values.mastodon.streaming.deployment.replicas }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels.global" . | nindent 6 }}
      {{- include "mastodon.selectorLabels.streaming" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.mastodon.streaming.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mastodon.selectorLabels.global" . | nindent 8 }}
        {{- include "mastodon.selectorLabels.streaming" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.mastodon.streaming.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-streaming
          securityContext:
            {{- toYaml .Values.mastodon.streaming.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.mastodon.image.repository }}:{{ .Values.mastodon.image.tag | default .Chart.AppVersion }}"
          args:
            - node
            - ./streaming
          imagePullPolicy: {{ .Values.mastodon.image.pullPolicy }}
          env:
            - name: STREAMING_CLUSTER_NUM
              value: {{ .Values.mastodon.streaming.settings.workers | quote }}
          {{- with .Values.mastodon.extraEnv.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mastodon.streaming.extraEnv.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "mastodon.fullname" . }}-env
            - secretRef:
                name: {{ include "mastodon.fullname" . }}-env
            {{- if .Values.mastodon.extraEnv.fromConfigMap }}
            - configMapRef:
                name: {{ .Values.mastodon.extraEnv.fromConfigMap }}
            {{- end }}
            {{- if .Values.mastodon.extraEnv.fromSecret }}
            - secretRef:
                name: {{ .Values.mastodon.extraEnv.fromSecret }}
            {{- end }}
          volumeMounts:
          {{- range .Values.mastodon.streaming.additionalMounts }}
            - {{- toYaml .volumeMount | nindent 14 }}
          {{- end }}
          ports:
            - name: streaming
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/streaming/health
              port: streaming
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/streaming/health
              port: streaming
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml .Values.mastodon.streaming.deployment.resources | nindent 12 }}
      volumes:
      {{- range .Values.mastodon.streaming.additionalMounts }}
        - {{- toYaml .volume | nindent 10 }}
      {{- end }}
      {{- with .Values.mastodon.streaming.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mastodon.streaming.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mastodon.streaming.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
