name: Release Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run on elk
        id: kube-lint-scan
        uses: stackrox/kube-linter-action@v1
        with:
          directory: charts/elk
          config: .kube-linter.yaml
